### ISSUE TITLE
question about drop_last=True on validation mode

### ISSUE THREAD

**Issue by DY112** [pytorch/examples#1063]
I don't know why this code use drop_last=True on validation mode.
Also, this code only uses batch_size dividable datas for calculating average top1,5 errors.
And then re-generate auxiliary validation data&dataloader for printing remaining logs.

Can anyone tell me why this code uses this method?

**Comment by hudeven** [comment]
Hi @DY112 , there are many examples in this repo. Could you share a code pointer of the example you are talking about?

**Comment by DY112** [comment]
Oh sorry.
My question was about imagenet training code.

https://github.com/pytorch/examples/blob/f82f5626b6432b8d0b08d58cc91f3bdbb355a772/imagenet/main.py#L256

**Comment by hudeven** [comment]
@DY112 Good question! Because `DistributedSampler` would pad the last uncompleted batch to become a full batch by default, which leads to wrong validation metrics. To get the correct metrics, we can either 1) use single GPU to run validation(it's slow though) or 2) use `DistributedSampler` for all batches until the last batch and use auxiliary dataset + regular Dataloader for the last batch. 

Read more in https://github.com/pytorch/examples/pull/980

**Comment by DY112** [comment]
Thank you for your kind and detail explanation @hudeven !!
