### ISSUE TITLE
why treating Alexnet/VGG differently in ImageNet example?

### ISSUE THREAD

**Issue by zym1010** [pytorch/examples#144]
in <https://github.com/pytorch/examples/blob/master/imagenet/main.py#L68-L72>, it seems that special care has to be taken when wrapping the module with `DataParallel`. Why is this the case? Also, I don't understand why for AlexNet and VGG, `features` is wrapped, yet `classifier` is not.

**Comment by soumith** [comment]
it is because they have very big fully connected layers at the end that are not suitable to DataParallel

**Comment by zym1010** [comment]
@soumith  thanks. Are you suggesting that fc layers for these networks are all stored on the same card?

**Comment by soumith** [comment]
yes

**Comment by cheerss** [comment]
Is there anyone know why "big fully connected layers at the end are not suitable to DataParallel"?

**Comment by colesbury** [comment]
@cheerss see https://arxiv.org/abs/1404.5997 [[pdf](https://arxiv.org/pdf/1404.5997.pdf)] (esp. sections 1-3):

> ... data parallelism is efficient when the amount of computation per weight is high (because
the weight is the unit being communicated)

It's not efficient to use DataParallel with the fully connected layers because they have lots of parameters, but relatively little computation. In theory, the fully connected layers are well suited for model parallelism, but it's kind of a pain to implement and the performance gain is small.

**Comment by cheerss** [comment]
@colesbury Thanks a lot !!
