### ISSUE TITLE
ipykernel_launcher.py: error: unrecognized arguments

### ISSUE THREAD

**Issue by ElizabethSvit** [pytorch/examples#369]
Came over this problem while running basic mnist example:

"usage: ipykernel_launcher.py [-h] [--batch-size N] [--test-batch-size N]
                             [--epochs N] [--lr LR] [--momentum M] [--no-cuda]
                             [--seed S] [--log-interval N]
ipykernel_launcher.py: error: unrecognized arguments: -f /Users/lizas/Library/Jupyter/runtime/kernel-678b777a-86db-48fc-b585-4e36387926c8.json"

Seems like ipython notebook version is outdated and one of the solutions could be changing 
args = parser.parse_args() to this line args = parser.parse_args(args=[])

**Comment by sakaia** [comment]
As a workaround, you need to use easydict instead of argparse for https://github.com/pytorch/examples/blob/master/mnist/main.py
Please refer following sites.
-  https://stackoverflow.com/questions/48796169/how-to-fix-ipykernel-launcher-py-error-unrecognized-arguments-in-jupyter
-  https://qiita.com/LittleWat/items/6e56857e1f97c842b261

**Comment by fucker119** [comment]
it's useful!!

**Comment by msaroufim** [comment]
Thank you for the helpful workaround @sakaia it seems like we no longer have any dependencies in in the minist example except for torch and torchvision so this should no longer be an issue https://github.com/pytorch/examples/blob/main/mnist/requirements.txt
