### ISSUE TITLE
Word Language Model just outputs errors

### ISSUE THREAD

**Issue by pasirauhala** [pytorch/examples#574]
### **Command I try to do:**
python main.py --cuda --save ./ --model LSTM --data /home/pasi/RaidHDD/AI/examples/word_language_model/data/wikitext-2 --epochs 10 --dropout 0.5 --nhid 650 --batch_size 1

### **Errors I get:**
Traceback (most recent call last):
  File "main.py", line 62, in <module>
    corpus = data.Corpus(args.data)
  File "/home/pasi/RaidHDD/AI/examples/word_language_model/data.py", line 24, in __init__
    self.valid = self.tokenize(os.path.join(path, 'valid.txt'))
  File "/home/pasi/RaidHDD/AI/examples/word_language_model/data.py", line 29, in tokenize
    assert os.path.exists(path)
AssertionError

**Comment by msaroufim** [comment]
I'm not sure which code you're running exactly since it seems to be imported within your own custom directory

But from your error message you can see `assert os.path.exists(path)` so I'd add a print statement like `print(path)` before that line to make sure your path does indeed exist and debug accordingly
