### ISSUE TITLE
No GPU usage for reinforcement learning

### ISSUE THREAD

**Issue by mahmoodn** [pytorch/examples#641]
I have build pytorch from source with `python setup.py install --user`. Now that I want to run the reinforcement learning example, I see that no process is offloaded to the GPU.

Also CPU usage is 100% which means one core only.
Should I do something more in order to utilize GPU? I don't see any option such as `--cuda` for this example.

**Comment by jacekplocharczyk** [comment]
I'm not an expert here but as far as I know it's hard to use GPU with the OpenAI Gym.

In examples here you have quite simple environments and because of that you neural nets are simple too - so GPU isn't necessary.
Gym has to run on CPU so in order to perform learning on GPU you have to copy all the variables from the CPU memory to the GPU.  
Doing this at each episode (or even worse at each timestamp) will create huge bottleneck in the memory bandwidth.  
To give you some example if the model sits on the GPU you will have to copy each observation to the GPU memory every time you would like to use this data and it will be more expensive for small models than doing everything on the CPU.

Hope this helps.
