### ISSUE TITLE
ImageNet's multiprocessing_distributed trainning

### ISSUE THREAD

**Issue by dongfangduoshou123** [pytorch/examples#655]
if not args.multiprocessing_distributed or (args.multiprocessing_distributed
                and args.rank % ngpus_per_node == 0):
            save_checkpoint({
                'epoch': epoch + 1,
                'arch': args.arch,
                'state_dict': model.state_dict(),
                'best_acc1': best_acc1,
                'optimizer' : optimizer.state_dict(),
            }, is_best)

Is the checkpoint save logic for ImageNet's multiprocessing_distributed trainning above may save a checkpoint on each node ?

for example:two nodes, each have 4 gpus(i.e ngpus_per_node=4)
then the rank on node1 is : 0, 1, 2, 3 and the rank on node2 is 4, 5, 6, 7
0 %ngpus_per_node == 0 will save a checkpoint (node1's rank 0)
4%ngpus_per_node ==0 will save a checkpoint(node2's rank4)
This is right? I think only the rank 0 need save checkpoint.

**Comment by 666XD** [comment]
Hey! I have the same question. 
Do you have the answer right now?

Base on the answer in this [post](https://discuss.pytorch.org/t/save-model-for-distributeddataparallel/47129), **pietern** replay that: "The model weights should be identical across processes and only the BN stats should be different."
So I think that mean all the model save from each node should be the same. But I am not so sure about that, and I don't have the machine to prove this.

**Comment by soumith** [comment]
cc: @mrshenli

**Comment by mrshenli** [comment]
> Is the checkpoint save logic for ImageNet's multiprocessing_distributed trainning above may save a checkpoint on each node ?

Yes, the code looks to me will save a checkpoint on every node. 

> I think only the rank 0 need save checkpoint.

This is true. But saving it on every node isn't wrong, and potentially will be faster when restoring from checkpoints. Because, if only rank 0 saves the model, when restoring, the the program will need to first load the checkpoint on rank 0 node, and then broadcast the model states to all other ranks. It's like file IO + network IO, and during this period of time, other ranks have to idle waiting. However, if every machine saves a checkpoint, then all nodes just need to read the checkpoint from local disk, and very likely will finish around the same time, avoiding additional delay caused by another broadcast.

**Comment by dongfangduoshou123** [comment]
@mrshenli  Now I know why, Thank you for your explain!
