### ISSUE TITLE
Example of MNIST using RNN

### ISSUE THREAD

**Issue by rakesh-malviya** [pytorch/examples#751]
Hi @osalpekar ,

I would like to implement an example of MNIST using RNN.

**Motivation:** Create pytorch example similar to Official Tensorflow Keras RNN example using MNIST [here](https://www.tensorflow.org/guide/keras/rnn)

I have written and tested the code by modifying following example on MNIST [here](https://github.com/pytorch/examples/tree/master/mnist) . Please let me know if I can raise a PR for this. 

Thanks and regards,
Rakesh

**Comment by osalpekar** [comment]
Hey @rakesh-malviya , Feel free to put up a PR, and we'll take a look!

**Comment by rakesh-malviya** [comment]
Thanks @osalpekar , for quick reply. I have submitted PR [here](https://github.com/pytorch/examples/pull/752).

**Comment by rakesh-malviya** [comment]
Hi @osalpekar, the PR is not moving forward. I am not sure, how much time it generally takes. I have resolved review comments. Please let me know something is required from me.

**Comment by soumith** [comment]
Hey Rakesh, I think part of the challenge was that you tagged/asked @osalpekar and he gave you his opinion and he didn't have information on how pytorch/examples is maintained.

We generally don't accept new examples unless they bring a lot of new value to the table. The goal of the `examples/` repo is not to maximize the number of examples, but to instead have a minimal set of concise examples with maximum information to the end user.

Because the entire turnaround of "asking about submitting a PR" to "submitting a PR" happened so quickly (within 48 hours), I missed it and didn't have a chance to respond.

I've been trying to figure out what to do with the PR, whether we should accept it or not. I don't have an answer yet. I am weighing the fact that we cover RNN as an example already in `word_language_model` and in the snli` examples.

**Comment by rakesh-malviya** [comment]
> Hey Rakesh, I think part of the challenge was that you tagged/asked @osalpekar and he gave you his opinion and he didn't have information on how pytorch/examples is maintained.
> 
> We generally don't accept new examples unless they bring a lot of new value to the table. The goal of the `examples/` repo is not to maximize the number of examples, but to instead have a minimal set of concise examples with maximum information to the end user.
> 
> Because the entire turnaround of "asking about submitting a PR" to "submitting a PR" happened so quickly (within 48 hours), I missed it and didn't have a chance to respond.
> 
> I've been trying to figure out what to do with the PR, whether we should accept it or not. I don't have an answer yet. I am weighing the fact that we cover RNN as an example already in `word_language_model` and in the snli` examples.

Thanks @soumith for reaching out. I think this PR is good for beginner level example of RNN. It is minimal and simple application of RNN.

**Comment by msaroufim** [comment]
Per soumith's comment closing
