### ISSUE TITLE
If set random seed across multi-gpu is necessary in DistributedDataParallel？

### ISSUE THREAD

**Issue by haohang96** [pytorch/examples#760]
Following imagenet-example: https://github.com/pytorch/examples/blob/master/imagenet/main.py, It seems that **seed** is not set in default (default is None): 
`parser.add_argument('--seed', default=None, type=int, help='seed for initializing training. ')`

But when we use DistributedDataParallel mode, if seed is not set, the initialized parameters across multi-gpu will be different, resulting in different model param is kept in different gpus during training process (although we only save ckpt in rank0 gpu). 

I am not sure whether this phenomenon will cause unknown errors, or may lead to an unstable results?  Is it safe for me not to set the initialization seed？

**Comment by eldarkurtic** [comment]
This is fine because rank-0 process will broadcast weights/states to other ranks: [pytorch docs](https://pytorch.org/tutorials/intermediate/ddp_tutorial.html#:~:text=Please%20note%2C%20as%20DDP%20broadcasts%20model%20states%20from%20rank%200%20process%20to%20all%20other%20processes%20in%20the%20DDP%20constructor%2C%20you%20don%E2%80%99t%20need%20to%20worry%20about%20different%20DDP%20processes%20start%20from%20different%20model%20parameter%20initial%20values.)
