### ISSUE TITLE
 DCGAN kernel_size 

### ISSUE THREAD

**Issue by yixiyixi5** [pytorch/examples#790]
DCGAN kernel_size why is 4,or why not 3(Isn't odd number more common)

**Comment by Shreerama9** [comment]
When the kernel size is even, it is less obvious which of the pixels should be at the origin, but this is not a problem. You have seen mostly odd-sized filter kernels because they are symmetric around the origin, which is a good property.
But in DCGAN , CNN layer with stride 2, this time the odd sized kernel convolution becomes not aligned one.
