### ISSUE TITLE
[AWS SageMaker] Multi-GPU some iterations periodically much slower than others

### ISSUE THREAD

**Issue by nollied** [pytorch/examples#834]
On AWS SageMaker running on an ml.p3.16xlarge (8 v100s, 64 vCPUs) instance has slow iteration times for every 5th print update. I have no idea what could be causing this. I made no changes to the code other than changing the data directory to default to where SageMaker stores the data in the container.

I set the number of workers to 50 (the number of vCPUs for the ml.p3.16xlarge instance is 64 so there is plenty CPU). also, I'm using resnet50 and a batch size of 1024.

it's also worth mentioning that with 8 v100 GPUs, it seems like to me that > 1 hour per epoch is quite excessive.

any ideas?

<img width="677" alt="Screen Shot 2020-10-15 at 7 28 55 PM" src="https://user-images.githubusercontent.com/26421036/96206089-ff338700-0f1c-11eb-87dd-556819d1218e.png">

**Comment by McCrearyD** [comment]
At first I thought it had to do with using AWS spot instances, but after further investigation it seems to happen for both spot and on demand instances.

**Comment by hyhuang00** [comment]
Same problem here.

**Comment by msaroufim** [comment]
It's difficult to debug without a repro but my best guess is this expected behavior because of a periodic weight synchronization since you're using so many GPUs. Try using no sync mode to confirm for sure.

![Screen Shot 2022-03-09 at 1 27 04 PM](https://user-images.githubusercontent.com/3282513/157539030-0a6d449e-346d-4de1-8c55-cbbf7d029404.png)
